syntax = "proto3";

package tactician;

// Service défini : Le C++ stream, le Web écoute.
service StreamPositions {
  // Le serveur envoie un flux continu de FrameData
  rpc Subscribe (SessionRequest) returns (stream FrameData);
}

message SessionRequest {
  string client_id = 1;
}

message FrameData {
  int64 timestamp = 1;
  repeated Player players = 2; // Liste des joueurs détectés
  Ball ball = 3;
}

message Player {
  int32 id = 1;
  float x = 2;
  float y = 3;

  // Définition de l'Enum à l'intérieur ou à l'extérieur du message
  enum TeamColor {
    UNKNOWN = 0; // Toujours avoir une valeur par défaut (0)
    TEAM_A = 1;  // Ex: Blancs
    TEAM_B = 2;  // Ex: Bleus
  }

  TeamColor team = 4; // C'est envoyé comme un petit entier (1 octet), ultra rapide.
}

message Ball {
  float x = 1;
  float y = 2;
  float speed = 3;
}